#!/bin/bash
# By yongcong.wang @ 2020-02-22

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

LANGUAGE=en

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=10000
HISTFILESIZE=20000

# share commands in different terminal
export PROMPT_COMMAND="history -a;"

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# tput setaf [0-7]: black, red, green, yellow, blue, magenta, cyan, white
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
BOLD=$(tput bold)
RESET=$(tput sgr0)

# set git status
git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ \1/'
}

git_status() {
  if git rev-parse --git-dir > /dev/null 2>&1 && \
     git status | grep "nothing to" > /dev/null 2>&1; then
    tput setaf 2 # green
  else
    tput setaf 1 # red
  fi
}

PS1='\[$RESET\]\u@\h:\[$BOLD\]\[$BLUE\]\w\[$(git_status)\]$(git_branch)\[$RESET\]$ '


# colored GCC warnings and errors
export GCC_COLORS='error=$RED:warning=$MAGENTA:note=$CYAN:\
                   caret=$GREEN:locus=01:quote=01'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# colored man page by set less term color
# export LESS='-R --use-color -Dd+r$Du+b'

# set vim mode
# set -o vi
export EDITOR=vim

# startx at login
if [[ -z "${DISPLAY}" && "${XDG_VTNR}" -eq 1 ]]; then
  exec startx
fi

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/opt/setup.bash ]; then
    source ~/opt/setup.bash
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && \
    eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"

    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'

    alias diff='diff --color=auto'
    alias ip='ip -color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# setxkbmap -layout us -option ctrl:nocaps

[ -f /opt/ros/neotic/setup.bash] && source ~/.fzf.bash

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
